<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kata Mars Nasa</title>
</head>

<body id="page-top" class="index">

<form action="/start" id="planForm" method="post">
    <label for="plan">Plan</label>

    <textarea id="plan" name="plan" rows="4" cols="50">5 5
3 3 N</textarea>


</form>
<button type="submit" form="planForm" value="Submit">Submit</button>


</body>

</html>

